### ISSUE TITLE
Arrow keys during task entry in timetrack.py prints error

### ISSUE THREAD

**Issue by japanjeff** [waynew/whelps#2]
Running timetrack.py in cmd or powershell in Windows 7 with Python 3.5.2, if you try to use arrow keys when entering a task title, After typing "Testing" and press the left arrow key, the screen looks like this:

```
00:00:03 - Task: TestingUnable to decode chr b'\xe0'
Traceback (most recent call last):
  File "timetrack.py", line 36, in _getch
    ch = ch.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 0: unexpected end of data
00:00:08 - Task: Testingb'\xe0'K
```

It looks like the key value gets appended onto the task title.

**Comment by waynew** [comment]
I think #3 sort of fixed this. I don't know if using the arrow key will work... And probably certainly not like you would think. But it should at least stop with the traceback part. A `--debug` flag has been introduced for debugging/logging.

If this still behaves oddly go ahead and reopen this :)

**Comment by japanjeff** [comment]
Wait, #3 is "Add a Gitter chat badge to README.md". Did you mean something else? Still shows traceback for me.

**Comment by waynew** [comment]
Yes, yes I did. I forgot that I didn't do a PR, I just pushed code lol. It was the commit that also closed #1 but if that doesn't fix can you run with the debug flag and post your log?

**Comment by japanjeff** [comment]
Here you go. I typed "Test", left-arrow, enter to accept input as is (including the extra `b'\xe0'K`), and then "q" to quit.

```
2016-11-07 10:48:18,059:INFO:MainThread:Logging information to timetracker.log
2016-11-07 10:48:18,059:DEBUG:MainThread:Args Namespace(args='', debug=True)
2016-11-07 10:48:18,059:DEBUG:MainThread:Hacking time... well, to record time spent hacking
2016-11-07 10:48:19,194:DEBUG:MainThread:Read character 'T'
2016-11-07 10:48:19,490:DEBUG:MainThread:Read character 'e'
2016-11-07 10:48:19,614:DEBUG:MainThread:Read character 's'
2016-11-07 10:48:19,755:DEBUG:MainThread:Read character 't'
2016-11-07 10:48:20,282:ERROR:MainThread:Unable to decode chr b'\xe0'
Traceback (most recent call last):
  File ".\timetrack.py", line 36, in _getch
    ch = ch.decode()
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 0: unexpected end of data
2016-11-07 10:48:20,286:DEBUG:MainThread:Read character "b'\\xe0'"
2016-11-07 10:48:20,286:DEBUG:MainThread:Read character 'K'
2016-11-07 10:48:20,976:DEBUG:MainThread:Read character '\r'
2016-11-07 10:48:20,977:INFO:MainThread:Storing task datetime.datetime(2016, 11, 7, 10, 48, 18, 58000)-datetime.datetime(2016, 11, 7, 10, 48, 20, 978000): "Testb'\\xe0'K"
2016-11-07 10:48:21,331:DEBUG:MainThread:Read character 'q'
2016-11-07 10:48:21,538:DEBUG:MainThread:Read character '\r'
2016-11-07 10:48:21,538:DEBUG:MainThread:Quitting...
2016-11-07 10:48:21,538:DEBUG:MainThread:Waiting for display thread to join...
2016-11-07 10:48:21,538:DEBUG:Thread-1:Stopping thread...
2016-11-07 10:48:21,538:DEBUG:MainThread:Display thread absorbed
2016-11-07 10:48:21,539:DEBUG:MainThread:Shut down
```

**Comment by waynew** [comment]
Okay, try _that_ one.
